import Database from 'better-sqlite3';
import fs from 'node:fs';
import path from 'node:path';
const dbPath=process.env.DB_PATH||path.resolve('backend/loanleads.db');
const outDir=process.env.BACKUP_DIR||path.resolve('backups');
fs.mkdirSync(outDir,{recursive:true});
const stamp=new Date().toISOString().replace(/[:.]/g,'-');
const out=path.join(outDir,`loanleads-${stamp}.db`);
const db=new Database(dbPath,{readonly:true});
db.backup(out).then(()=>{db.close(); console.log(`Backup created: ${out}`)}).catch(e=>{db.close();console.error(e);process.exit(1)});
